// Contract guard: content-script code never talks to the heatsync API directly.
//
// A content script's requests are subject to the HOST page's CORS, and
// heatsync.org does not list twitch.tv / kick.com / youtube.com as allowed
// origins — so a direct fetch/XHR from a multichat module is rejected before
// any handler runs, and the failure surfaces as a bare, unhelpful "network
// error". Every API call therefore goes through the background service worker
// (apiFetch → 'api_fetch', uploads → 'api_upload'), which reaches the API under
// host_permissions and attaches the stored auth token.
//
// This is not hypothetical. `uploadMediaFile` was the single module that opened
// its own XMLHttpRequest — chosen so it could report upload progress — and it
// failed on every host page for every pasted image, while working when the same
// code ran on heatsync.org itself, which is same-origin. It shipped that way.
// A percentage is not worth a transport that only works where nobody uses it.
//
// Source-level assertion on purpose: these modules run inside the host page and
// can't be imported here.

import { describe, expect, test } from 'bun:test'
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const MC_DIR = join(ROOT, 'src/multichat')

const modules = readdirSync(MC_DIR).filter((f) => f.endsWith('.js'))

// Comments explain the rule; they shouldn't trip it.
function stripComments(src) {
  return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '')
}

describe('multichat modules reach the API only through the background worker', () => {
  test.each(modules)('%s opens no request of its own at API_URL', (file) => {
    const src = stripComments(readFileSync(join(MC_DIR, file), 'utf8'))

    // `new XMLHttpRequest()` anywhere in a multichat module is the exact shape
    // of the bug — there is no case for it now that progress isn't reported.
    expect(src, `${file} constructs an XMLHttpRequest`).not.toMatch(/new\s+XMLHttpRequest\b/)

    // A direct fetch to our own API is the same mistake wearing a different
    // name. Fetching third-party CDNs (7TV, twitch thumbnails) is fine — those
    // send permissive CORS — so only API_URL is off limits.
    const apiFetches = src.match(/fetch\s*\(\s*[`'"]?\$\{?\s*CONFIG\.API_URL/g) || []
    expect(apiFetches, `${file} fetches CONFIG.API_URL directly`).toHaveLength(0)
  })

  test('the upload path routes through the api_upload relay', () => {
    const src = readFileSync(join(MC_DIR, 'input.js'), 'utf8')
    expect(src).toMatch(/type:\s*'api_upload'/)
  })

  test('background.js answers api_upload', () => {
    const bg = readFileSync(join(ROOT, 'chrome/background.js'), 'utf8')
    expect(bg).toMatch(/message\.type === 'api_upload'/)
    // The boundary is generated by fetch from the FormData body. Setting
    // Content-Type by hand omits it and the server can't parse the body.
    const handler = bg.slice(bg.indexOf("message.type === 'api_upload'"))
    const body = handler.slice(0, handler.indexOf('register_self_twitch_id'))
    expect(body).not.toMatch(/['"]Content-Type['"]\s*\]?\s*[:=]\s*['"]multipart/i)

    // The upload URL must leave the relay absolute. The server answers with
    // '/uploads/<file>' and the only consumer appends it to the chat composer,
    // so a relative URL sends a message that STARTS WITH A SLASH — Twitch reads
    // it as a slash command and replies "Unrecognized command: /uploads/...".
    // The image never reaches chat. Feed/thread are saved by the render
    // chokepoint absolutizing; a chat send has no chokepoint, the text IS the
    // wire payload.
    expect(body, 'api_upload relays the raw server url').toMatch(/sendResponse\(\{\s*ok:\s*true,\s*url:\s*absUrl\(/)
  })
})
